export enum ScenariosActionTypes {
    FETCH_SCENARIOS = '[Scenarios] Fetch Scenarios Action',
    FETCH_SCENARIOS_SUCCESS = '[Scenarios] Fetch Scenarios Success Action',
    FETCH_SCENARIOS_FAILURE = '[Scenarios] Fetch Scenarios Failure Action',
    MOVE_SCENARIO = '[Scenarios] Move Scenario Action',
    MOVE_SCENARIO_SUCCESS = '[Scenarios] Move Scenario Success Action',
    MOVE_SCENARIO_FAILURE = '[Scenarios] Move Scenario Failure Action',
    DELETE_SCENARIO = '[Scenarios] Delete Scenario Action',
    DELETE_SCENARIO_SUCCESS = '[Scenarios] Delete Scenario Success Action',
    DELETE_SCENARIO_FAILURE = '[Scenarios] Delete Scenario Failure Action',
    FETCH_SCENARIO = '[Scenarios] Fetch Scenario Action',
    FETCH_SCENARIO_SUCCESS = '[Scenarios] Fetch Scenario Success Action',
    FETCH_SCENARIO_FAILURE = '[Scenarios] Fetch Scenario Failure Action',
    DELETE_SCENARIO_FROM_LIST = '[Scenarios] Delete Scenario From List Action',
    DELETE_SCENARIO_FROM_LIST_SUCCESS = '[Scenarios] Delete Scenario From List Success Action',
    DELETE_SCENARIO_FROM_LIST_FAILURE = '[Scenarios] Delete Scenario From List Failure Action',
    UPDATE_SCENARIO = '[Scenarios] Update Scenario Action',
    UPDATE_SCENARIO_SUCCESS = '[Scenarios] Update Scenario Success Action',
    UPDATE_SCENARIO_FAILURE = '[Scenarios] Update Scenario Failure Action',
    CREATE_SCENARIO = '[Scenarios] Create Scenario Action',
    CREATE_SCENARIO_SUCCESS = '[Scenarios] Create Scenario Success Action',
    CREATE_SCENARIO_FAILURE = '[Scenarios] Create Scenario Failure Action',
}
