export enum SceneriesActionTypes {
    FETCH_SCENERIES = '[Sceneries] Fetch Sceneries Action',
    FETCH_SCENERIES_SUCCESS = '[Sceneries] Fetch Sceneries Success Action',
    FETCH_SCENERIES_FAILURE = '[Sceneries] Fetch Sceneries Failure Action',
    MOVE_SCENARIO = '[Sceneries] Move Scenario Action',
    MOVE_SCENARIO_SUCCESS = '[Sceneries] Move Scenario Success Action',
    MOVE_SCENARIO_FAILURE = '[Sceneries] Move Scenario Failure Action',
    DELETE_SCENARIO = '[Sceneries] Delete Scenario Action',
    DELETE_SCENARIO_SUCCESS = '[Sceneries] Delete Scenario Success Action',
    DELETE_SCENARIO_FAILURE = '[Sceneries] Delete Scenario Failure Action',
    FETCH_SCENARIO = '[Sceneries] Fetch Scenario Action',
    FETCH_SCENARIO_SUCCESS = '[Sceneries] Fetch Scenario Success Action',
    FETCH_SCENARIO_FAILURE = '[Sceneries] Fetch Scenario Failure Action',
    DELETE_SCENARIO_FROM_LIST = '[Sceneries] Delete Scenario From List Action',
    DELETE_SCENARIO_FROM_LIST_SUCCESS = '[Sceneries] Delete Scenario From List Success Action',
    DELETE_SCENARIO_FROM_LIST_FAILURE = '[Sceneries] Delete Scenario From List Failure Action',
    UPDATE_SCENARIO = '[Sceneries] Update Scenario Action',
    UPDATE_SCENARIO_SUCCESS = '[Sceneries] Update Scenario Success Action',
    UPDATE_SCENARIO_FAILURE = '[Sceneries] Update Scenario Failure Action',
    CREATE_SCENARIO = '[Sceneries] Create Scenario Action',
    CREATE_SCENARIO_SUCCESS = '[Sceneries] Create Scenario Success Action',
    CREATE_SCENARIO_FAILURE = '[Sceneries] Create Scenario Failure Action',
}
